Integrating PartnerIDs
xmidt-org/ancla pull request #79
Opened 2021-09-16 19:13 UTC by mtrinh11

2021-09-16 20:18 UTC, kristinapathak commented on transport.go
> +		case "Basic":
```suggestion
		case "basic":
```

2021-09-16 20:18 UTC, kristinapathak commented on transport.go
> +			var configurableString string
We can add this string (I would name it something like `basicPartnerIDsHeader` to the `transportConfig` that we pass into the create decoder function.  Then, if it's empty, we should set it to a const called `DefaultBasicPartnerIDsHeader`.  I would add this empty string check above the creation of this function to return (ie around line 82).

2021-09-16 20:18 UTC, kristinapathak commented on transport.go
> +			whatdoesthisinterfacemean, _ := bascule.GetNestedAttribute(authToken.Attributes(), basculechecks.PartnerKeys()...)
Might want to rename `whatdoesthisinterfacemean` 🙂

2021-09-16 20:18 UTC, kristinapathak commented on transport.go
> +				return nil, errGettingPartnerIDs
```suggestion
				return nil, fmt.Errorf("%w: %v", errGettingPartnerIDs, err)
```
Usually we don't want to lose any error information.

2021-09-17 18:01 UTC, kristinapathak reviewed
Looking good so far!

2021-09-21 06:25 UTC, joe94 requested changes

2021-09-21 06:25 UTC, joe94 commented on transport.go
> +		}
we could make this its own helper function. Something like `extractPartnerIDs` which returns both a slice and an error type?

2021-09-21 06:25 UTC, joe94 commented on transport_test.go
> +			default:
Go doesn't require the default case to be explicit when empty

2021-09-21 18:54 UTC, kristinapathak approved these changes
Looks great!

2021-09-21 18:54 UTC, kristinapathak commented on transport.go
> +	DefaultBasicPartnerIDsHeader = "X-Xmidt-Partner-Id"
```suggestion
	DefaultBasicPartnerIDsHeader = "X-Xmidt-Partner-Ids"
```

2021-09-21 20:26 UTC, joe94 approved these changes
LGTM!

2021-09-21 20:56 UTC, merged